Change limit of filed value on ps_customized_data so that it can accepts max 1024 characters
PrestaShop/classic-theme pull request #100
Opened 2023-01-30 16:29 UTC by lartist

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Change limit of filed value on ps_customized_data so that it can accepts max 1024 characters
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27579
| Sponsor company   | 
| How to test?      | https://github.com/PrestaShop/PrestaShop/issues/27579

2023-01-30 20:30 UTC, mflasquin approved these changes

2023-01-30 21:06 UTC, kpodemski requested changes
Careful. There's a relation between the theme and core versions to have it working.

I'm blocking it for now because I see a risk of having something dedicated to 8.1 only (or 9) too soon in classic.

2023-01-31 09:21 UTC, jolelievre approved these changes

2023-01-31 11:02 UTC, kpodemski approved these changes, later dismissed

2023-01-31 14:46 UTC, jolelievre approved these changes

2023-02-01 12:58 UTC, paulnoelcholot commented
Hello @lartist,

I have tested your PR and I found some bugs : 

On FO product page : 
![image](https://user-images.githubusercontent.com/112863083/216048242-dd7c5148-6e97-43f7-95e7-060f3c050d10.png)

On FO checkout page : 
![image](https://user-images.githubusercontent.com/112863083/216048301-d92aa4f7-b7fe-47e0-80c4-ffc65ff1dd75.png)

On BO order : 
![image](https://user-images.githubusercontent.com/112863083/216048375-c321311c-1625-47de-b096-ab816cdd09c5.png)
if the text has spaces

On BO order : 
![image](https://user-images.githubusercontent.com/112863083/216048627-f3ac08d3-56c2-4e59-8223-336000abbe3f.png)
if the text hasn't spaces

2023-02-02 09:35 UTC, paulnoelcholot commented
Hello @lartist 

My apologies, after a second test, the problem was related to my environment.
Everything is ok for me :tada: 

Thanks!

2023-02-02 09:35 UTC, paulnoelcholot approved these changes

2023-02-07 17:33 UTC, merged