Adapt template for manufacturer presenter
PrestaShop/classic-theme pull request #112
Opened 2023-04-24 12:19 UTC by Hlavtox

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Template modification for https://github.com/PrestaShop/PrestaShop/pull/31309. Allows use of standard image arrays and new image formats.
| Type?             | refactor
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      | Install https://github.com/PrestaShop/PrestaShop/pull/31309, install this. See that it works and you have <picture> tags on /brands and on manufacturer image on product page.

2023-05-04 09:49 UTC, kpodemski commented
@Hlavtox I think we can merge it because QA tested it in your core PR?

2023-05-09 10:31 UTC, kpodemski requested changes
Hey @Hlavtox 

I assigned it to v3.0 milestone, could you:
- bump classic to 3.0.0
- bump min compat to v9?

2023-05-09 11:04 UTC, Hlavtox commented
@kpodemski Done ✅

2023-05-09 11:07 UTC, kpodemski approved these changes

2023-05-09 11:08 UTC, merged