Update product.tpl
PrestaShop/classic-theme pull request #12
Opened 2022-03-16 10:58 UTC by lucasvavon

Hi,
While developing a client's site, we noticed that the product availability date was displayed in the product details tab.
I propose to display it directly next to the product.
The date will be more easily visible for the customers.
Lucas,
Piment Bleu Agency (FR)

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | display availability date directly next to the product
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Possible impacts? | none

2022-03-17 09:40 UTC, Thierry-Pimentbleu commented
good idea

2022-03-17 09:41 UTC, NeOMakinG commented
@lucasvavon 

Thanks for the contribution

When you submit an improvement, you need to first create an issue on the `PrestaShop/PrestaShop` repository, because this choice depends on product choices, we need to talk about it before, in order to validate it.

If the team doesn't agree with this choice, your work can be abandoned and this is really something both of us don't want: wasting time...

@PrestaShop/product-team for information

@lucasvavon could you please create an issue?

2022-03-17 09:43 UTC, NeOMakinG commented
@PrestaShop/prestashop-maintainers 

Do we work on improving Classic? I have a doubt about it, did we state the fact that we fix bugs only?

2022-03-18 08:25 UTC, kpodemski commented
@NeOMakinG 

I think we should accept some improvements, maybe not those with breaking changes :-)

2022-03-22 08:35 UTC, Progi1984 requested changes
Glad to see you @lucasvavon (I believe we have discussed together at the PS Day 2021).

Thank you for your contribution.

Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?

Thanks :+1:

2022-03-22 09:33 UTC, lucasvavon commented
Hi @Progi1984, I think you met my boss @Thierry-Pimentbleu instead.
I have introduce an issue in this PR : [Update product-details](https://github.com/PrestaShop/classic-theme/pull/11).
Do you understand what we wanted to improve ?

2022-04-19 12:06 UTC, matks commented
Hello @lucasvavon I'm sorry you mentioned a PR not an issue 😅 

It seems you maybe have troubles seeing how we process contributions. Don't hesitate to come and discuss on the Slack channel to ease this contribution https://www.prestashop-project.org/slack/

2022-08-25 21:02 UTC, kpodemski commented
Hi @lucasvavon,

Since we have had no news from you since April, I will follow [our guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests), and I'll close this pull request as it seems stale. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2022-08-25 21:02 UTC, closed without merging