Allow ordering as a guest, even after a you made an account
PrestaShop/classic-theme pull request #17
Opened 2022-03-24 12:40 UTC by Hlavtox

Everything is here - https://github.com/PrestaShop/PrestaShop/pull/25353

2022-03-24 12:41 UTC, kpodemski approved these changes

2022-03-25 08:31 UTC, NeOMakinG approved these changes
LGTM but we need to wait for the core PR

2022-03-29 08:52 UTC, matthieu-rolland requested changes
I put a `request change` to be sure the PR is not merged until it can be merged, feel free to cancel it when it's time

2022-04-14 09:25 UTC, MeKeyCool approved these changes

2023-01-29 15:25 UTC, closed without merging