Add category additional description
PrestaShop/classic-theme pull request #18
Opened 2022-03-24 13:06 UTC by Hlavtox

Theme PR for https://github.com/PrestaShop/PrestaShop/pull/27292

2022-03-25 08:30 UTC, NeOMakinG approved these changes
Looks fine but waiting for the core PR to be merged

2022-03-25 09:41 UTC, kpodemski approved these changes

2022-03-29 08:53 UTC, matthieu-rolland requested changes, later dismissed
request change is to block the PR until it can be merged, feel free to cancel it when it's time

2022-04-06 10:13 UTC, khouloudbelguith reviewed
Hi @Hlavtox,

It is ok :heavy_check_mark: 
While testing this PR, to not have a conflict with the classic them, I renamed this theme to classic-theme in config/theme.yml and I changed the preview.png

I checked a category with

- empty products
- Category with pagination
- I tried to change the page
- I tried to use some filter & sort => ok

https://user-images.githubusercontent.com/16067358/161952131-801a3ecb-469d-45a5-9eca-7d4316cb97c3.mp4

to test this theme, I followed these steps:

1. git clone git@github.com:PrestaShop/classic-theme.git
2. cd classic-theme
3. git prc origin 18 develop
4. npm install && npm run build

Thanks!

2022-04-06 10:17 UTC, merged