Custom
PrestaShop/classic-theme pull request #25
Opened 2022-04-11 20:23 UTC by unlocomqx

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Contains fixes and refactorings related to this PR https://github.com/PrestaShop/PrestaShop/pull/12422
| Type?             | refacto
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Create an order containing customizations, the order details in the customer account should display correct quantities

![image](https://user-images.githubusercontent.com/793712/162824490-f3664c6d-d33d-42e7-b41d-4f9f06736556.png)

The order return should work fine as well because the customization info is already included in the order details as pointed out in https://github.com/PrestaShop/PrestaShop/pull/12422/commits/5dc00a8e10b1c14a3d5b43b73d8164187406a714

| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

2022-04-12 08:08 UTC, NeOMakinG approved these changes
On a code point of view, looks fine, for the rest, the QA needs to test it with your PR!

2022-04-12 10:58 UTC, unlocomqx commented
@NeOMakinG Thank you
I mentioned this PR in the base PR

2022-04-20 08:50 UTC, matks approved these changes

2022-06-21 09:41 UTC, atomiix commented
@marwachelly any reason you removed "Waiting for QA" and added "Waiting for author"?

2022-06-21 09:46 UTC, unlocomqx commented
It was related to the original PR https://github.com/PrestaShop/PrestaShop/pull/12422
I replied there directly https://github.com/PrestaShop/PrestaShop/pull/12422#issuecomment-1104308043

2022-08-25 20:59 UTC, kpodemski requested changes
I'm blocking this to make sure related PR will be merged first. I hope we can plan it for version 9.0 of the PrestaShop!

2022-08-25 21:22 UTC, unlocomqx commented
@kpodemski It's cool, hopefully it will be merged. it will fix a few existing bugs here and there + will allow to cleanly fix some hidden bugs

2023-02-08 14:34 UTC, hibatallahAouadni reviewed
Hello @unlocomqx 

The issue #10912 is already fixed on develop as you can see in the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/217559247-69ebab34-be4a-4748-bcd9-be9cba6f2095.png)

While with your two PRs, the customized product image and the Total price are not displayed, and there's some notices displayed above the table, as you can see in the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/217559916-7930ca16-8172-4391-bb89-2242127167fb.png)

Please check and feedback.

Thanks!

2023-02-08 15:52 UTC, unlocomqx commented
@hibatallahAouadni It could be that you are not in the `custom` branch of the PrestaShop repo

Please check again, thanks

2023-02-09 15:29 UTC, hibatallahAouadni approved these changes
Hello @unlocomqx 

Thanks for your patience and hard working :pray: 
Finally it works like a charm :raised_hands: :clap: 
LGTM, QA :heavy_check_mark: 

[pr_12422.webm](https://user-images.githubusercontent.com/23308427/217854613-bc3918db-7468-4a3d-990c-1e1e30a888d8.webm)

PS: automated tests are launched : https://github.com/hibatallahAouadni/testing_pr/actions/runs/4135636932

Thanks!

2023-02-09 19:20 UTC, unlocomqx commented
Thank you @hibatallahAouadni 🚀 
Amazing work!

2023-02-09 19:35 UTC, kpodemski approved these changes

2023-02-09 19:36 UTC, merged

2023-02-09 19:38 UTC, kpodemski commented
Thank you again @unlocomqx 

I really hope you'll participate in the project even more! We need help from experienced developers like you. We'll do what we can to make the process better and quicker! Thank you for your patience ❤️

2023-02-09 19:47 UTC, unlocomqx commented
Thank you @kpodemski for merging
It's fine, I know it's a huge project and issues/PRs can take time to be resolved/merged
I'll do what I can to contribute even more, thank you 💯