Update ps_emailsubscription.tpl
PrestaShop/classic-theme pull request #44
Opened 2022-07-09 09:41 UTC by LouisAUTHIE

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Corrects the centering issue on prestashop 8.0.x
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/29018
| How to test?      | Go to front office index page
| Possible impacts? | Nothing

2022-07-09 09:52 UTC, okom3pom approved these changes

2022-07-09 20:27 UTC, Hlavtox requested changes
Hi @LouisAUTHIE, thank you for your contribution, however, it must be done differently. This code is wrong on multiple levels.

`<div class="block_newsletter container col-lg-8 col-md-12 col-sm-12" id="blockEmailSubscription_{$hookName}">`

- `container `class should be used only for limiting the screen width. 
- `col-lg-8 col-md-12 col-sm-12` are used wrongly and without a `row `class. These classes should be used for responsivity, not limiting the width.

This is a block that can be shown anywhere and it should be styled by CSS for the specific hook.

Ping @NeOMakinG

2022-07-10 09:24 UTC, okom3pom commented
One of the problems is that block social is not displayed because there is no url for the social networks. 

We could add urls to the installation of the social module.

So the https://github.com/PrestaShop/PrestaShop/issues/29018 is not an issue ?

2022-07-10 11:26 UTC, LouisAUTHIE commented
I have done a new proposition with a style modification that should do the same but cleaner. Thanks guys for the reviews.

2022-07-12 05:37 UTC, NeOMakinG commented on _dev/css/components/footer.scss
> +  float:none;
```suggestion
  float: none;
```

2022-07-12 05:39 UTC, NeOMakinG commented on _dev/css/components/footer.scss
> +  float: none;
```suggestion
  float: none;
  margin: auto;
```

2022-07-12 05:41 UTC, NeOMakinG commented
Hey @LouisAUTHIE and thanks for the contribution!

@Hlavtox is probably right, this block shouldn't be centered everywhere as it can be used in any hooks!

I guess even the `margin: auto;` isn't a good practice, do we want to center the block inside any hook like in a sidebar/column?

2022-08-16 09:34 UTC, matks commented
@LouisAUTHIE Hello, will you continue this topic or shall we take it 😉 ?

2022-09-28 20:34 UTC, matks commented
Hi,

Since we had no news from you for more than 30 days, I will follow [our guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) and I'll close this pull request as it seems stale. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2022-09-28 20:34 UTC, closed without merging